### ISSUE TITLE
validate implementation assumptions

### ISSUE THREAD

**Issue by dryajov** [libp2p/js-libp2p-circuit#15]
I want to document some of the assumptions made around the javascript circuit implementation. I'll list them bellow to make sure they are vetted and properly validated before we ship circuit.

1) **Circuit is a transport**

Circuit is implemented as a transport and uses the existing swarm transport flow to plug itself into the connection processing flow, this is done by pushing the circuit as a transport module, from where libp2p and swarm will, for example, start the listening part of circuit, just as it would for any other transport.

2) **Circuit will add a default `/p2p-circuit/ipfs/QmAddr` if an explicit addr is not provided**

Circuit makes some assumptions around how `/p2p-circuit` addrs in the IPFS swarm config are handled
   - When circuit is being instantiated, it will check if an explicit circuit addr (`/p2p-circuit/...`)  is provided in the config, if it is, circuit will use that addr to listen on explicitly, including dialing to an optionally provided relay. If no explicit `/p2p-circuit` addr is provided, circuit will add a default one that looks like this - `/p2p-circuit/ipfs/Qm...`. The reason this is done, is to allow for point **1** above. The JS implementation uses peer addresses in to enable/disable a transport and control weather that transport should be used to dial or not, without having at least one circuit addres, swarm/libp2p would simply skip circuit and not enable or use it. For example https://github.com/libp2p/js-libp2p-swarm/blob/7144f0beaf6cce5f4b5e8a6bcf45699df45fa157/src/transport.js#L50 or https://github.com/libp2p/js-libp2p/blob/master/src/index.js#L167.
       - I know that this might be an argument against making circuit a transport, but IMO there is currently no other artifact that would allow plugin in to the dialing/listening flow without touching/reimplementing parts of swarm/libp2p.
   - Circuit will make all swarm addresses a `/p2p-circuit` addr. This was originally done because the assumption that announcing `/p2p-circuit` addrs was ok, and marking all addrs as `/p2p-circuit` seemed increase the changes of a peer being reached over a relay. This might not be the case anymore, but before reimplementing that part, I would love to hear some feedback for and against doing it this way.

3) **Circuit will probe every incoming connection for relay support using the `CAN_HOP` message**
   - Every time a `peer-mux-established` event is fired circuit will send the incoming peer the `CAN_HOP` message in order to prob it for relay functionality, if it is a relay it will add it to its internal table, on `peer-mux-closed` it will remove it from the internal table.

4) **Circuit keeps its own internal relay table**
    - Circuit currently keeps its own table of relays and it doesn't use the peerbook or any other existing facility to store the list of know relays. This was done mainly because from within circuit, I don't have access to the peerbook and using the provided swarm internal connection table seemed dirty, plus that table holds everything - relay and non relay connections/peers...

5) **Circuit uses swarm for dialing**
   - AFAIK, we _can't_ avoid using swarm, since it would require reimplementing all the dialing and transport logic inside circuit, which I don't think is the right thing to do. That said, circuit uses swarm only to get the current peer info as well as the `.dial` method.

@diasdavid @lgierth @dignifiedquire @whyrusleeping @vyzo

**Comment by diasdavid** [comment]
> 1. Circuit is implemented as a transport 

This is 70% correct to say. Yes, it should offer the same interface, but instead of opening a socket, it will mount a protocol, instead of dialing its own socket, it uses swarm do dial a stream.

> and uses the existing swarm transport flow to plug itself into the connection processing flow, this is done by pushing the circuit as a transport module, from where libp2p and swarm will, for example, start the listening part of circuit, just as it would for any other transport.

Circuit should be a backup dialing solution if all the real transports fail. Circuit should not come on the transports array in Swarm, instead it should be something that "is enabled or disabled".

> 2. Circuit will add a default /p2p-circuit/ipfs/QmAddr if an explicit addr is not provided

I believe this point is rather confusion as it stands described. What I see is that it is mixing the implementation in libp2p with how it gets configured and set up by js-ipfs.

If the IPFS config is the one saying "enable circuit" through a multiaddr, then js-ipfs just needs to pass an option down to libp2p. If the IPFS config wants to say "dial to these relays", then that option needs to happen to. Note that dialing to a Relay node is the same thing as dialing to a bootstraper node, it is just opening a connection that then streams can be open on top.

> 3. Circuit will probe every incoming connection for relay support using the CAN_HOP message

Sounds good 👌🏽

> 4. Circuit keeps its own internal relay table

Although I can agree on having a PeerSet of Relays, do note that you have access to the PeerBook since you pass the Swarm instance.

> 5. Circuit uses swarm for dialing

That is correct. Just mind the way deps are installed. Ideally, tests in libp2p-circuit should use a Swarm mock and tests in libp2p-swarm should use circuit, otherwise if we decide to change Swarm or Circuit API, we will have a hell of circular dep management (which I already had to unwrap two, libp2p-crypto-secp256k1+libp2p-crypto and libp2p+libp2p-dht)

**Comment by dryajov** [comment]
>Circuit should be a backup dialing solution if all the real transports fail. 
👌 

> Circuit should not come on the transports array in Swarm, instead it should be something that "is enabled or disabled".

I think we already discussed this and came to the agreement that we will treat circuit as a transport specifically because of the implementation benefits that reusing that pipeline gives us - here are a couple of comments on the main circuit PR (closed because you couldn't act as a reviewer on a PR that you opened):

- https://github.com/libp2p/js-libp2p-circuit/pull/9#discussion_r116524180
- https://github.com/libp2p/js-libp2p-circuit/pull/9#discussion_r116526567
- https://github.com/libp2p/js-libp2p-circuit/pull/9#discussion_r116667173

You might have to click on the outdated links to expand the comments. I should also document this in a clear and concise way - I tried to capture it in the README but we probably need a gitbhub issue so that we can refer to it easily as well, at least for now. 

In summary we can have both - the circuit behave as a transport and also only enable/disable it as required, so there is really no conflict.

> If the IPFS config is the one saying "enable circuit" through a multiaddr, then js-ipfs just needs to pass an option down to libp2p. If the IPFS config wants to say "dial to these relays", then that option needs to happen to. 

👍 with a few caveats. There are tree parts to circuit - Dialer, Listener (STOP) and Relay (HOP). The dialer and listener parts can be always enabled (well, as long as we have multiplex otherwise it doesn't make sense) as there is no reason not to have the ability to dial or listen over a relay. This is not to say that we HAVE to do it this way, just that I don't see a strong argument not to do it that way. As far as config goes, they should behave the same way a regular transport does with the only exception that if no `/p2p-circuit/` multiaddr is present then circuit will be implicitly added, because of the reasons outlined above - makes sense to be able to dial/listen (STOP) for relayed connections across the board, plus having a bare `/p2p-circuit` in the config is just plain confusing :)

The Relay (HOP) is the part that should allow to be enabled/disabled explicitly through configs - and this is how it works right now.

> Note that dialing to a Relay node is the same thing as dialing to a bootstraper node, it is just opening a connection that then streams can be open on top.

Yep, this should just work - since every connection will be probed for `HOP` support, so just the fact of connecting to bootstrap nodes should discover relays as well.

> That is correct. Just mind the way deps are installed. Ideally, tests in libp2p-circuit should use a Swarm mock and tests in libp2p-swarm should use circuit, otherwise if we decide to change Swarm or Circuit API, we will have a hell of circular dep management (which I already had to unwrap two, libp2p-crypto-secp256k1+libp2p-crypto and libp2p+libp2p-dht)

👌 absolutely - all accounted for.

**Comment by diasdavid** [comment]
> In summary we can have both - the circuit behave as a transport and also only enable/disable it as required, so there is really no conflict.

Exactly, have the cake and eat it too.

**Comment by dryajov** [comment]
@diasdavid 

> Exactly, have the cake and eat it too.

Are you OK then with having circuit in the transports array as long as we can control both when dialing happens as well as enable/disable `HOP` with configs?

**Comment by diasdavid** [comment]
@dryajov I'm 50% ok, go ahead with it and make all the tests on js-libp2p pass + interop with go-ipfs, once I get to https://github.com/libp2p/js-libp2p-swarm/issues/24 that might change :)

**Comment by dryajov** [comment]
Awesome! I get it, we might end up refactoring swarm which might require reworking transports and other things. But worry not - all the circuit logic is isolated from the transport interface, so even if there is going to be some refactoring that requires touching that, it should not affect the underlying circuit implementation itself.

**Comment by diasdavid** [comment]
@dryajov are all of these notes present on the Circuit spec?

**Comment by dryajov** [comment]
@diasdavid yes, this has been integrated into the circuit spec where it makes sense. Some of this are just exposing some implementation asumptions that only matter in the context of js-ipfs.

**Comment by diasdavid** [comment]
Closing then :)
