### ISSUE TITLE
Identify implementation differences with GO

### ISSUE THREAD

**Issue by dryajov** [libp2p/js-libp2p-circuit#16]
This issue is to capture and discuss any significant implementation differences between the GO and JS circuit relay implementations. 

@vyzo @stebalien @whyrusleeping @lgierth @diasdavid

**Comment by vyzo** [comment]
While debugging an issue with the js implementation on irc, we came to the realization that we can optimize secio handshake latency by having the relay immediately respond with OK, before receiving OK from STOP.

This allows the relay to immediately start piping the dialer's input, and saves a roundtrip in secio handshake -- half a roundtrip in each side of the connection.
This is a potentially important optimization; see https://github.com/libp2p/go-libp2p-circuit/issues/16

**Comment by diasdavid** [comment]
What differences are left?

**Comment by dryajov** [comment]
The one that vyzo brought up here, is already implemented in js land. That's the only one I have come across so far.

**Comment by diasdavid** [comment]
@dryajov are there still differences? Parts where js-libp2p-circuit is not spec compliant?

**Comment by dryajov** [comment]
No, we're 100% spec compliant.

**Comment by diasdavid** [comment]
Can this be closed then?
