### ISSUE TITLE
peer:connect event for connections incoming over relay missing

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p-circuit#26]
If peerA dials peerB over peerR, peerA emits `peer:connect, peerB` properly.
Yet peerB does not emit `peer:connect, peerA`.
Additionally peerA seems to be missing from peerB's peerBook

Fix was to make peerB dial peerA, but this broke the event on peerA's side

How to test this:
 - Clone https://github.com/mkg20001/libp2p-exchange-direct and run `npm i`
 - Run `npx aegir test -t node`, tests should pass
 - Revert commit e317a3a033cb29f8f454de3748ffc8bd7fb20e04
 - Run `npx aegir test -t node`, tests fail

~~Edit: After `npm i`, `npm i mkg20001/interface-data-exchange` needs to be run as  the version with the tests is still not published.~~

**Comment by jacobheun** [comment]
@mkg20001 I added some tests at https://github.com/libp2p/js-libp2p-switch/pull/275 to check for circuit relay connections and the `peer-mux-established` event, which causes libp2p to fire the `peer:connect` event. It's being triggered by the listener. It looks like libp2p-exchange is using an older version of libp2p, perhaps that is causing the event not to trigger?

**Comment by mkg20001** [comment]
@jacobheun Might be the reason. I'll see if upgrading fixes it.

**Comment by dryajov** [comment]
This seems to be a legitimate issue, I think this might solve it - https://github.com/libp2p/js-libp2p-circuit/pull/30

**Comment by jacobheun** [comment]
#30 looks good but I don't think it's causing this issue. libp2p-switch emits the `peer-mux-established` event after a peer has been identified during muxing. libp2p listens for that event and emits `peer:connect`. If identification isn't turned on, the event won't trigger.
