### ISSUE TITLE
Support Peer Routing Interface

### ISSUE THREAD

**Issue by guysv** [libp2p/js-libp2p-circuit#46]
Today, when a libp2p node wants to connect to a peer via the circuit relay, the p2p-relay multiaddr is explicitly specified.

In case the peer discovery was dynamic (e.g. a pubsub channel peer) the application has to take the following steps to establish a direct connection:

1. if already connected, done.
2. search peer via node.peerRouting.findPeer() If found, dial, done
3. dial /p2p-circuit/ipfs/peer-id, if connected, done.
4. connection failed

Step 3 is redundant. the application should not be bothered with the connection method. If the circuit-relay module would implement the peer-router API, we could abstract the usage of the relay from the application. (You could argue that step 1 is redundant too, but it is actually handled by the DHT module)

There are couple of loose ends to this feature, like:
- should Circuit.findPeer(<id>) automatically return /p2p-relay/ipfs/<id> or should it find an explicit relay before declaring a route is found

I would love to hear your feedback about this idea!

**Comment by dryajov** [comment]
Circuit relay is a fallback mechanism. When peers are dialed, circuit is tried last. If an address without any transports is specified, such as `/ipfs/Qm...`, libp2p/switch would dial on all compatible transports first and eventually fall back to circuit relay if all other mechanisms failed. Also, circuit relay is implemented as a transport and it sits lower in the stack than peer routing/discovery.

If I understand your use case correctly, you should be able to provide `/ipfs/Qm..` of the remote peer and it should work, albeit most likely not over circuit if another transport succeeded first.

Connecting explicitly over circuit can be useful when the topology of the network is well known, for example when the remote peer is behind a NAT, etc. Eventually, an upgrade mechanism should be provided, where a relayed connection is only used to negotiate a better connection/route. Take a look at the `dialme` here - https://github.com/libp2p/specs/pull/64.

**Comment by guysv** [comment]
@dryajov I tried to use `/ipfs/Qm..` directly:
I deployed a mininet NAT network using [this script](https://github.com/mininet/mininet/blob/master/examples/natnet.py), erected a go-ipfs node in each host, enabled HOP in the "internet" node (h0), ipfs-connected `h1<->h0<->h2` and then tried:
```
mininet> h1 ipfs swarm connect /ipfs/QmfEBNNYhbadwqhbMbojKa8RmR2qFGgmv2zDLC6JA9uJD2
Error: connect QmfEBNNYhbadwqhbMbojKa8RmR2qFGgmv2zDLC6JA9uJD2 failure: dial attempt failed: <peer.ID Qm*2graar> --> <peer.ID Qm*A9uJD2> dial attempt failed: dial tcp4 192.168.2.100:4001: i/o timeout
mininet> h1 ipfs swarm connect /p2p-circuit/ipfs/QmfEBNNYhbadwqhbMbojKa8RmR2qFGgmv2zDLC6JA9uJD2
connect QmfEBNNYhbadwqhbMbojKa8RmR2qFGgmv2zDLC6JA9uJD2 success
```

It seems that `/p2p-circuit` was needed explicitly. Isn't that a bug?

**Comment by dryajov** [comment]
Yes lets confirm it in the js implementation, otherwise this seems like a bug in Go right now.

**Comment by guysv** [comment]
I tested it with js-ipfs and it turns out you were right, this works on js-ipfs.
I guess this issue could be closed now. I should notify go-libp2p-circuit about their unexpected behavior though..
