### ISSUE TITLE
Relay use cases

### ISSUE THREAD

**Issue by dryajov** [libp2p/js-libp2p-circuit#6]
I thought it would be a good idea to document use cases for the relay, some are obvious, but some are not, at least to me :)

- allow peers that can't speak the same transports to communicate
- enable private networks, such as corporate networks to to use relay nodes as gateway nodes
- if a relay node is running on a a wifi router, peers connected to that router should be able to talk to each other over that relay.
   - this probably needs some way of ranking relays/peers by priority. Do we currently have something like that? 
- ...

@diasdavid @lgierth @whyrusleeping

**Comment by diasdavid** [comment]
@dryajov, I believe this has been captured by the updated spec. If you feel something is missing from there, could you submit an update there? [Relay Spec PR](https://github.com/libp2p/specs/pull/15)
