### ISSUE TITLE
Comments on implementation 

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/js-libp2p-circuit#8]
Hey, Chatted with @diasdavid and @lgierth in the sprint call

First off,
I'm not sold on the idea of having an `ls` type command here. It has a weird conflation of responsibilities and also has very weird security implications. I think this should be left out, and if its functionality we really want, it can be mounted as a separate protocol.

I also think that we should have some form of status codes in response to setting up streams. When its successful, we should send back a success message. When a relay setup fails, we should send back a failure message. The current setup simply drops the stream when a failure occurs. This is going to cause headaches in the future. We can also potentially use this response to signal capabilities of the relay node, or perhaps information about rate limiting. In any case, that stuff can come later, we can simply pass extra stuff later with the status information.

**Comment by diasdavid** [comment]
> I'm not sold on the idea of having an ls type command here.

As we discussed in the call, we can make `ls` as a separate protocol that gets mounted if `/ipfs/relay/ls`

Which brings me to ask again, why do have a `/ipfs` on the protocol handle? (`/ipfs/relay/circuit`).

**Comment by diasdavid** [comment]
> I also think that we should have some form of status codes in response to setting up streams. 

Sounds good. Let's start with:

- 200 Ok - Will relay it for you
- 404 Not Found - I can't make that connection

**Comment by dryajov** [comment]
@whyrusleeping 

👍 on the response codes, not having them has been pretty _weird_ just from a purely `do whats expected` perspective - every request usually has a response.

Also agree on capabilities, we should be able to say if a node is a dialing node or not, and that should/could help prioritizing which relays are dialed.

The `ls` is important to the whole flow, because, the basic case assumes that the circuit-relay would not dial for you, only relay on its already existing connections. I'm either way on weather adding it to the relay or as a separate swarm handler, in fact since we're basically exposing the swarms peerbook, it should probably be there.

**Comment by dryajov** [comment]
@diasdavid Those look good. I'll add the capabilities since we're at it as well. It should make developing/debugging easier at the very least, and could potentially help making better decisions when selecting relays.

```
200
active
/circuit-relay
```

```
200
passive
/listener
```

```
500
<err message>
```

**Comment by dryajov** [comment]
Clarification on the active/passive vs listener/circuit-relay parts. 

* Active/Passive 
   * active - you will dial for me
   * passive - only if you already connected to the peer I want

* /circuit-relay vs /listener - 
   * /circuit-relay - you hit the middle point in the connection flow
   * /listener - you've reached you're destination

Both this things have bit me during development a few times, nothing stopping them from slipping through as bugs and becoming security issues later on. More explicit is better - IMHO.

**Comment by lgierth** [comment]
> Which brings me to ask again, why do have a /ipfs on the protocol handle? (/ipfs/relay/circuit).

Yes these should be changed to `/libp2p/relay/circuit` -- has already been updated a while ago in the spec: https://github.com/libp2p/specs/tree/master/relay#overview

**Comment by dryajov** [comment]
I'll update those to match /libp2p, how about /ipfs -> /p2p? That seems like a bigger effort, since it would have to be updated everywhere.

**Comment by lgierth** [comment]
> I'm not sold on the idea of having an ls type command here. It has a weird conflation of responsibilities and also has very weird security implications. I think this should be left out, and if its functionality we really want, it can be mounted as a separate protocol.

Agreed :+1: this is a discovery concern and doesn't have much to do with relaying itself

**Comment by lgierth** [comment]
> how about /ipfs -> /p2p? That seems like a bigger effort, since it would have to be updated everywhere.

Yeah changing to /p2p is a different beast -- @whyrusleeping has an idea for that I think

**Comment by lgierth** [comment]
On `ls`: it is about service discovery. We should potentially start writing our supported protocols into the DHT, so that we can run queries a la "nodes speaking protocol X". For example if you're looking for relay nodes, you query for nodes speaking `/libp2p/relay/circuit/1.0.0/hop`.

We can name this "service routing" or so.

**Comment by whyrusleeping** [comment]
> Yeah changing to /p2p is a different beast

For this, i think we can do a two stage rollout.

First stage is modifying go-multiaddr to accept *either* `/ipfs/` or `/p2p/`, converting to the same underlying code, but defaulting to `/ipfs/` still. These nodes would be able to parse either sort of address if it was given in text form (I think we don't actually pass addresses in strings anywhere, but just to be safe)

Stage two is to switch that code over to defaulting to `/p2p/`

This might not actually be a big deal, and we could probably just do both steps at the same time

**Comment by dryajov** [comment]
@whyrusleeping 

out of curiosity, is there anyway of aliasing a proto name - having two different strings point to the same proto id? That along switching (at least the js implementation) from using strings for protos to using contstans, should make it a smooth transition? Hypothetical question, mostly 😄

**Comment by whyrusleeping** [comment]
@dryajov not currently, but it shouldnt be too difficult to do

**Comment by dryajov** [comment]
@whyrusleeping next question, should we do that?

**Comment by whyrusleeping** [comment]
Yeah, thats what i'm thinking

**Comment by dryajov** [comment]
@whyrusleeping ah, I guess I didn't fully understand your initial comment. Tanks!

**Comment by diasdavid** [comment]
[Relay Spec PR](https://github.com/libp2p/specs/pull/15)
